-- Seed data for internships table
INSERT INTO public.internships (
    title,
    company,
    location,
    duration,
    stipend,
    type,
    skills,
    description,
    requirements,
    application_deadline,
    contact_email,
    posted_by,
    status
) VALUES 
(
    'Software Development Intern',
    'Tech Innovations Pvt Ltd',
    'Bangalore, Remote',
    '3 months',
    25000,
    'private',
    ARRAY['JavaScript', 'React', 'Node.js'],
    'Join our development team to work on cutting-edge web applications and enhance your skills in modern technologies.',
    'Pursuing B.Tech/M.Tech in Computer Science or related field with good knowledge of JavaScript and React.',
    '2024-02-29',
    'careers@techinnovations.com',
    NULL,
    'active'
),
(
    'Data Science Intern',
    'Data Insights Co.',
    'Mumbai',
    '6 months',
    30000,
    'private',
    ARRAY['Python', 'Machine Learning', 'Pandas', 'SQL'],
    'Work with our data science team on real-world projects involving machine learning and data analysis.',
    'Strong background in mathematics and statistics, proficiency in Python, and experience with data analysis libraries.',
    '2024-02-15',
    'hr@datainsights.co',
    NULL,
    'active'
),
(
    'Marketing Intern',
    'BrandBoost Solutions',
    'Delhi',
    '3 months',
    15000,
    'private',
    ARRAY['Digital Marketing', 'Social Media', 'Content Creation', 'Analytics'],
    'Assist in developing marketing campaigns and analyzing their effectiveness across various channels.',
    'Marketing or business degree preferred with knowledge of social media platforms and basic analytics tools.',
    '2024-02-20',
    'jobs@brandboost.com',
    NULL,
    'active'
),
(
    'Research Intern - AI',
    'National Research Lab',
    'Hyderabad',
    '4 months',
    20000,
    'govt',
    ARRAY['Python', 'TensorFlow', 'Research', 'AI'],
    'Contribute to groundbreaking research in artificial intelligence and machine learning algorithms.',
    'Pursuing Master''s or PhD in Computer Science, AI, or related field with research experience.',
    '2024-02-10',
    'research@nrl.gov.in',
    NULL,
    'active'
);